### ISSUE TITLE
not working with AoE2DE_s.exe (Age of Empires II: Definitive Edition

### ISSUE THREAD

**Issue by thiagolinhares** [SFTtech/sftscrollbugfixer#1]
Hello,

I tried your fix with AoE2DE and it won't work.

Steps made to make it work with Steam:
Working folder: ~/.steam/steam/steamapps/common/AoE2DE
Rename AoE2DE_s.exe to AoE2DE_s-ORIG.exe
Rename age2_x1_fixed.exe and .ini to AoE2DE_s.exe and <...>.ini
Adjust exe_file=AoE2DE_s-ORIG.exe inside AoE2DE_s.ini
Go to Steam Library, and set launch options for Age of Empires II: Definitive Edition:
/c ~/.steam/steam/steamapps/common/AoE2DE/AoE2DE_s.exe
(that way, steam won't try to update the game because of changed exe file).
It runs your executable and then starts the game. But the bug is still there.

Wine Debbuger says:

ini file               Z:\home\thiago\.steam\steam\steamapps\common\AoE2DE\AoE2D
E_s.ini
exe file               AoE2DE_s-ORIG.exe
dll file               fix_scrollbug32.dll
start command          AoE2DE_s-ORIG.exe /c /home/thiago/.steam/steam/steamapps/
common/AoE2DE/AoE2DE_s.exe
start cwd              Z:\home\thiago\.steam\steam\steamapps\common\AoE2DE
dll file [full path]   Z:\home\thiago\.steam\steam\steamapps\common\AoE2DE\fix_s
crollbug32.dll
exe file [full path]   Z:\home\thiago\.steam\steam\steamapps\common\AoE2DE\AoE2D
E_s-ORIG.exe
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Applicati
on Data\openvr\openvrpaths.vrpath
Setting breakpad minidump AppID = 813780
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198003414423 [API loaded no]
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Applicati
on Data\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Applicati
on Data\openvr\openvrpaths.vrpath
2020/03/29 22:57:20 : inf - BT! - SockInit: SOCK_FD_SET_SIZE = 8192
2020/03/29 22:57:20 : inf - WRN - SockConnect: failed (error 10013 - ATLAS_NOTINTABLE: Undefined error.).
Process of pid=006f has terminated
No process loaded, cannot execute 'echo Modules:'
Cannot get info on module while no process is loaded
No process loaded, cannot execute 'echo Threads:'
process  tid      prio (all id:s are in hex)
00000008 steam.exe
        0000002a    0
        00000009    0
0000000c services.exe
        00000026    0
        00000020    0
        00000018    0
        00000011    0
        0000000e    0
        0000000d    0
0000000f plugplay.exe
        00000015    0
        00000014    0
        00000010    0
00000016 winedevice.exe
        0000001d    0
        0000001c    0
        0000001b    0
        0000001a    0
        00000019    0
        00000017    0
0000001e winedevice.exe
        00000023    0
        00000022    0
        00000021    0
        0000001f    0
00000024 winedevice.exe
        00000029    0
        00000028    0
        00000027    0
        00000025    0
0000002b explorer.exe
        00000031    0
        00000030    0
        0000002d    0
        0000002c    0
00000034 AoE2DE_s.exe
        00000035    0
00000036 wineconsole.exe
        00000037    0
00000038 AoE2DE_s-ORIG.exe
        00000075    0
        00000071    0
        0000006e    0
        0000006d    0
        0000006c    0
        0000006b    0
        0000005e    0
        0000005d    0
        0000005c    0
        0000005b    0
        0000005a   -2
        00000059   -2
        00000058   -2
        00000057   -2
        00000056   -2
        00000055    0
        00000054    0
        00000053    0
        00000049    0
        00000048    0
        00000047    0
        00000046    0
        00000045    0
        00000044    0
        00000043    0
        00000040    0
        0000003f    0
        0000003e    0
        0000003d    0
        0000003c    0
        00000039    0

**Comment by mic-e** [comment]
Hi, thanks for the report...

I think the problem with DE is that it's a 64-bit executable, so the scrollbugfix (as well as its depends) need to be recompiled as 64-bit as well.

That should in theory be enough to do the trick. I tried that quickly but it didn't work...

Unfortunately, I have basically zero experience with using Windows build tools, and also basically zero motivation in getting to know them any further... still... I'd like this to work in DE

Ideally we'd get this whole thing to run with mingw so we can build it on Linux with a proper Makefile, but I don't have a lot of experience with mingw either.

**Comment by Thaodan** [comment]
See #2

**Comment by Thaodan** [comment]
This could be no longer needed with latest proton because of:
https://github.com/ValveSoftware/wine/commit/d9855df17f905da97b4bd92227427c4f899babf1

**Comment by TheJJ** [comment]
Yes, the proper bugfix is upstream in wine, and it was only a matter of time until it was also included in proton :)

**Comment by TheJJ** [comment]
The bug report was https://bugs.winehq.org/show_bug.cgi?id=30814, the fix https://source.winehq.org/git/wine.git/commitdiff/d9855df17f905da97b4bd92227427c4f899babf1, which is upstream since wine 5.9.
